# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://****************************
    username: *****
    password: *****
    hikari:
      max-lifetime: 500000


  cache:
    type: redis
  redis:
    host: 127.0.0.1
    port: ****
    jedis:
      pool:
        max-active: 8
        max-wait: 1000
        max-idle: 30
        min-idle: 10
    lettuce:
      shutdown-timeout: 0
    timeout: 1200
#    password: ********
server:
  port: *********
  tomcat:
    uri-encoding: UTF-8
mybatis-plus:
  global-config:
    db-config:
      table-prefix: *******

